Add Scinteel Synthete spectre.
PathOfBuildingCommunity/PathOfBuilding pull request #1351
Opened 2020-09-05 08:25 UTC by tgavankar

2020-09-05 21:55 UTC, ppoelzl requested changes

2020-09-05 21:55 UTC, ppoelzl commented on Export/Skills/spectre.txt
> -#mods
That seems to be an editing error. The rest looks good though. Please fix it so we can accept your PR.

2020-09-05 22:13 UTC, tgavankar commented
Sorry, haven't used git/github in 10 yrs, super rusty. Should be OK now?

2020-09-06 20:40 UTC, ppoelzl approved these changes
All good now!

2020-09-16 11:42 UTC, merged