Adding malachai artifice replica support
PathOfBuildingCommunity/PathOfBuilding pull request #1365
Opened 2020-09-13 03:06 UTC by uilman

Adding malachai artifice original stub; needs work to allow the config options to appear, but otherwise is correct

2020-09-13 13:05 UTC, uilman commented
There are *some* potential side effects; with the ring equipped, you always see the config options for EE/ alt ailments. I personally believe this is easier to use because you don't need to swap to your proccing skill in order to change those settings, but it is inconsistent with other things

2020-09-25 05:23 UTC, ppoelzl requested changes
I think it is acceptable to always show EE, especially since you'll likely use a different skill than your main skill to proc it.

2020-09-25 05:23 UTC, ppoelzl commented on Modules/ModParser-3_0.lua
> +		local plus = 25
I think it is fine to hardcode these values without refactoring into variables, like with the other mods.

2020-10-07 20:22 UTC, ppoelzl approved these changes
LGTM now.

2020-10-16 19:15 UTC, merged