Fixes #1519, #1562 - Thread of Hope socketed in cluster jewel
PathOfBuildingCommunity/PathOfBuilding pull request #1628
Opened 2020-10-09 16:41 UTC by Wires77

Fixes #1519
Fixes #1562

2020-10-11 18:44 UTC, ppoelzl requested changes
The changes to `TreeTab.lua` seem to be unrelated?

2020-10-11 18:48 UTC, Wires77 commented
Correct, just some code clean-up I spotted along the way.  Doesn't change any functionality

2020-10-11 20:50 UTC, ppoelzl requested changes
For unrelated changes, please open separate PRs. The boy scout rule applies to the campground, not the entire forest.

2020-10-14 08:09 UTC, ppoelzl approved these changes

2020-10-16 19:15 UTC, merged