Support for a missing "Jinxed Juju" unique amulet mod
PathOfBuildingCommunity/PathOfBuilding pull request #1830
Opened 2021-01-09 20:36 UTC by mullinger

Previously, the special mod the the Jinxed Juju Amulet was not supported:

> 10% of Damage from Hits is taken from your Spectres' Life before you

This commit adds support for the mod in regards to the damage taken calculations.

![grafik](https://user-images.githubusercontent.com/645185/104108127-78dfd480-52c2-11eb-9a81-fd90f5cd1ee1.png)

I assume that the calculations in-game might be slightly different, though the differences are probably in the sub-percent range.
This patch should give a pretty good addition for now.

2021-01-10 02:32 UTC, Regisle commented
This needs to only be active if your specters have enough life to take the damage (make a config option) as there are builds who use the amulet without specters

2021-01-10 06:56 UTC, mullinger commented
@Regisle Very good point, thanks for your comment.
Instead of adding yet another config options I thought about checking if the player actually has an active spectre skill.

Without active spectre skill, or of the spectre skill is disabled the mod from the amulet will not be applied.

What do you think?

2021-01-13 00:40 UTC, ppoelzl commented
There should be some kind of calculation on how much damage is actually transferable to the spectre.
Also in your code you spelled it "specter", not "spectre", which is our preferred spelling @mullinger

2021-01-13 00:50 UTC, Wires77 commented
> 
> 
> There should be some kind of calculation on how much damage is actually transferable to the spectre.

Eh, I'm not sure this is necessary, even the weakest spectres have almost 10k health, so you'd need to take 100k damage before that's something to worry about.

I'm all for not adding more config options, too, so just basing it off of the player having an active spectre skill seems like the right way to go to me.

2021-01-13 08:13 UTC, mullinger commented
E.g. Apes have unbuffed 16k max HP without **any** investment .
At lvl 20 gem you can have 3 apes with a total pool of around 48k HP.

I'm down with any decision (Config option or without) as I can see the benefits of both implementations. Just need a decision :-)

2021-01-15 09:17 UTC, deathbeam commented
This is not 10% less damage taken, this should work like mind over matter because its same mechanic.

2021-02-06 08:38 UTC, Wires77 requested changes
If we're fine assuming the spectres will always have enough health to give you the damage mitigation, I've added a suggestion for a simpler way to implement this

2021-02-06 08:38 UTC, Wires77 commented on Modules/CalcPerform.lua
> +			end
This loop is already done on https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/3e28ad5599ebcddf8377cb3cbb433fefe4fb7ff4/Modules/CalcPerform.lua#L767-L770

~~Can you change this code to use that variable, instead?~~

Actually, on second thought, you can do this entirely in ModParser.lua, see that for a suggestion

2021-02-06 08:38 UTC, Wires77 commented on Modules/ModParser.lua
> +	["damage from hits is taken from your spectres' life before you"] = "DamageFromHitsTakenFromSpectres",
I haven't tested this, but see if this works instead

```suggestion
	["damage from hits is taken from your spectres' life before you"] = { "DamageTakenWhenHit", tag = { type = "SkillName", skillName = "Raise Spectre" } },
```

2021-04-04 05:28 UTC, Wires77 commented
@deathbeam is correct, this implementation isn't right.  It should act as another multiplier on top of other reduced * less damage modifiers you have.

I can merge this as a 10% less damage taken, and open an issue to fix it properly later, or we can keep it open and do it properly from the start.  React if you don't want to comment but want to vote on one over the other.

✔️ Merge now, fix later
❌ Don't merge until properly implemented

2021-04-04 14:28 UTC, ppoelzl commented
No need to rush out unfinished features "just because".

2023-04-04 09:22 UTC, gbhwnpbshb commented
I'm a bit confused

2023-04-28 10:01 UTC, QuickStick123 commented
Superseded by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/5943

2023-04-28 10:01 UTC, closed without merging