Fix: Oos activation frequency with more multipliers to cast speed
PathOfBuildingCommunity/PathOfBuilding pull request #2261
Opened 2021-02-24 16:46 UTC by pundm

This PR tries/seems to fix #1936

![image](https://user-images.githubusercontent.com/54453318/109034065-8c56cb80-76c7-11eb-9cdf-74b797cce7fb.png)

Pastebin for testing purposes: https://pastebin.com/UkUK74xu

2021-02-24 17:18 UTC, pundm commented
I just tried to create a fake jewel with less/reduced cast speed and I don't know if my solution still holds up. Could someone more knowledgeable have a look?

2021-02-24 23:51 UTC, Wires77 approved these changes
This looks like it's working to me

2021-02-25 12:16 UTC, Nostrademous requested changes

2021-02-25 12:16 UTC, Nostrademous commented on Data/Skills/act_int.lua
> +		activeSkill.skillData.hitTimeOverride = activeSkill.skillData.hitFrequency / (1 + activeSkill.skillModList:Sum("INC", activeSkill.skillCfg, "Speed") / 100) / activeSkill.skillModList:More(activeSki
This works but calcLib.mod() could be used for the entire tail end of this to make it cleaner: https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/dev/Modules/CalcTools.lua#L16-L18

`activeSkill.skillData.hitTimeOverride = activeSkill.skillData.hitFrequency / calcLib.mod(activeSkill.skillModList, activeSkill.skillCfg, "Speed")`

2021-02-25 12:16 UTC, Nostrademous commented on Export/Skills/act_int.txt
> +		activeSkill.skillData.hitTimeOverride = activeSkill.skillData.hitFrequency / (1 + activeSkill.skillModList:Sum("INC", activeSkill.skillCfg, "Speed") / 100) / activeSkill.skillModList:More(activeSki
same as above

2021-02-25 12:27 UTC, pundm commented
changed it according to your feedback and it still works. thanks!

2021-02-25 12:49 UTC, Nostrademous approved these changes

2021-02-25 12:51 UTC, Nostrademous commented
You are doing great work and your help is greatly appreciated. Thanks!

2021-03-03 05:59 UTC, ppoelzl approved these changes
LGTM.

2021-03-03 06:33 UTC, merged