Atziri Rule implementation
PathOfBuildingCommunity/PathOfBuilding pull request #2597
Opened 2021-04-18 13:05 UTC by Nostrademous

Start

2021-05-30 02:28 UTC, Ydoum commented
Any update on this?

2022-01-31 21:20 UTC, Nostrademous commented
Fixes #2677

2022-02-01 02:20 UTC, Wires77 requested changes
Looks pretty good, needs a couple of cleanup commits is all

2022-02-01 02:20 UTC, Wires77 commented on src/Modules/ModParser.lua
> +end
Was there a reason this couldn't be combined with `triggerExtraSkill`?

2022-02-01 02:20 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +			if not specialCase then
?

2022-02-01 02:20 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +				env.player.mainSkill.infoTrigger = ""
I don't think this is needed
```suggestion
				env.player.mainSkill.infoTrigger = ""
```

2022-02-01 02:20 UTC, Wires77 commented on src/Modules/CalcOffence.lua
> +					skillData.triggerRate = skillData.triggerRate * (cachedSourceSkill.ActiveSkill.skillData.dpsMultiplier or 1)
Can we add this to the breakdown, too?  Eff. Trigger Rate on the Calcs tab doesn't end up showing one, but it's higher than the others and people will probably want to know where it comes from.

Didn't realize triggered skills could be supported by unleash, actually

2022-02-01 04:41 UTC, Nostrademous commented on src/Modules/CalcPerform.lua
> +			if not specialCase then
leftover accident... always true ... just removing

2022-02-01 04:41 UTC, Nostrademous commented on src/Modules/CalcPerform.lua
> +				env.player.mainSkill.infoTrigger = ""
correct, another left over

2022-02-03 03:54 UTC, closed without merging