Fix Punishment Curse doesn't affect the DPS while select "Enemy is on Low Life"
PathOfBuildingCommunity/PathOfBuilding pull request #2638
Opened 2021-04-21 17:37 UTC by Typepluto

Fix Punishment Curse doesn't affect the DPS while select "Enemy is on Low Life"

Issue #2607 Punishment Curse DPS calculation/For Effective DPS:Is the enemy on Low Life check bug

2021-04-21 22:46 UTC, Wires77 requested changes
The top of this file says it is auto-generated.  Please make the same change to `src/Export/Skills/act_str.txt` otherwise your changes will be overwritten by the exporter when we do a release

2021-04-21 23:37 UTC, Typepluto commented
I make the same change to the correct file.
Thank you for your kindly remind!

2021-04-22 05:10 UTC, Wires77 approved these changes

2021-04-22 05:58 UTC, LocalIdentity approved these changes

2021-04-22 05:58 UTC, merged