Adds: functionality for blood artist
PathOfBuildingCommunity/PathOfBuilding pull request #2767
Opened 2021-05-11 11:52 UTC by pundm

fixes #2696 

Once something is equipped/skilled with 'if you spent life recently', it adds a checkbox to trigger that condition on/off
![image](https://user-images.githubusercontent.com/54453318/117810238-6ae59480-b25f-11eb-928b-759b0e286eaa.png)

For a test i created a fake jewel with the exact same stats as the 'Blood Artist' notable, leaving out the condition.

(with condition checked)
![image](https://user-images.githubusercontent.com/54453318/117810463-b6983e00-b25f-11eb-910c-962908dcd0ed.png)

Jewel
![image](https://user-images.githubusercontent.com/54453318/117810387-9cf6f680-b25f-11eb-8d0b-d0a1c4bb54e6.png)
![image](https://user-images.githubusercontent.com/54453318/117810570-ddef0b00-b25f-11eb-9052-38ba76e88b66.png)

Test-PoB
`eNrtPWlv20iWn0e_gjCwi11EcepgHcwmu_AVxz1x4lhJ3D1fGkWyaLFNkQpJ2VYG89_3FamDlEilrGSmscBOD2KZevXq3Ucd9Kv_eZwkzr3OizhLXx_gQ3Tg6DTIwji9fX3w-dOb5_Lgf_578OpKleMP0fEsTsw3_z34y6vqs5Poe528PvDogVOq_FaXX5ao6O-AaqrScqyz9FL9keXnWfj64H2W6gPHV2kYl68PPqi7AydIVFG8VxP9-mAUwNgDRxWBTsOT9fOj6gEgO3AmKk5HWXCny_M8m02B5gPnPtYPl1kIgBeXVx-uPzUmjtPmxED4X15dJWqu81GpSqeAfwA78K9u9dsY0N-rZAZ4pHSpOJQYCXLwYueoUzWBf58ycDTVOlwNwIeCCvavhr3K9VkU6aCM7_VJHpcnY5UGay5o37inwl7OkjKeJrHOG4T1UvV2CzlGqA_4U1aq5PRqtIZllHN0yD2OCf9njMrW9kEYcgk_ZBR5nEncN-4mLscwrDmfi1wkxSEhAnl498jjBBT6ZFrNyIvbNC71XkOvsrjI0r0l1BxoKaSTbOLHaZtTSykthx7d3z6N3EuVqpOsWCu018zexZFuQWLZi_VsZIfzGiKGHaSh80rnEP1Ke3KfNGBUrl2Tsd6gda2_NiEx63XiU_24BuvXACBsQeJeJV-kDb8TaAfCJuROCu-zsko0NtJcQXHp4h2xN3hpoC_SYE0scnch_pzmutD5fSNo75qiPWShY5tAaQZe61u95ld43iHnO2d6p3UwPodce63KtQg8gg897mLBBdvpW-sR_XCVzAxwS2ZyF9oukdnBb8oLAgQRHDNU_8C7sLSFR9DhTuhuyfVq5yzV-e18NI51smbK69dmJbXmoKb0XGYzTZsfK8qeytS9KpoOxpnYzU8N3zKEXlYuNeRFGBHqjWIB_bwRV3n2h6mOkqcNO8on2WwdJQnxyE6-a_gm27TXnq_G8yIOIMlWBee1DmdBK4jhXs9ZVXqX2b2egBdUlSIUzI2ajPQq6DiBantDAGKXeSZJ15D-1HJUliq4O83CW2s5V7M8acSbOAeZFXEjJfZXx2vgD1Dkn6hpI__0lyLGsSwnWANvTrAjY9yOyxSaL-tJNkZsztQrKhBpVmzM8rw_jDfArad4M0taRXi_ou_iNmSp_ES_dNAjllqFEvUa_VX2AMSMTVNaWPh7A_pSPX6_uXmT6_Tb3Bp_C9xqgrM0nOXGtq3n2ByxPc2rF1XXbj5dTKZZXjrQYpdHQZDN0vKtKsavD8IoINSNKMUuxVxyyXToKqwDzOEfpiKtUBBgSPBm6LVWyQSkd1L_aiZWQanzGheFwYS4OAoE4r4MsIcg7ijXp8qPmOtj7IsgQn5N24lKgqLi7CKdzkonrTr_SVwEv_uzKDL9_QFwmlcrE2dv3pydfLr4crYQRnNIYWzm93Q28U3XWf80ywQ15EhXYdMJsiRR00KHrw8ilRSAOw4X9jaCdBGUVvDQsS4WAGygb1Qe5DHo0gbYtJtWJFdtvw2kacitAME4VKLtBfZpPtXGEAtbmS2itg101QRbQdadqx2DVX9spwYdqLkV5KpGsoI-S_RRnJhsbCe1S3CEOpHbwUNWzWN_VlpaW9XpWNFhqnsrBpuFrRXFdfFkhXtRX9rALjKZna1B3WKtjVMdabBiS2-uosQndafTRShexrtXlQsVTgHx-FxPiuM55Ls3RmobSyMtAMiE-QxwhzpSs8Q8_zhTSVzOXx-kcdJ8_q5eoq2eFuPsYTSbTmtMxm0LkPu7d_U3R0m5QGKmWZJfM2dorNZej6pKsvq94qBagI3TIJmF0PwuEvuK9UT5ZvID59Ys1p6YPLMgRacmk4dLPookM7VmFs6dZRG9MZuZyNDyl1dA3WL4eZL5KiHr6WpeCT5oAeDVLAbRhTGgx0Klt7M4rdqZrzXXF5W7V3IDgvXE_H6pSxWqUr24KEEmL4xgXlTkwKdOJKZB3OIuqBkHskyKMqX_JgkVZZdxWq2dj2aTSQZqv4IwWapiUluYDePoe4wvtA-RBHqJYP503lfWs4XClCZWjC8H_nSuTuBpUv4IU5sYbHlajvv5LI1NQvkBhlrjrdkZr9LYT2UmS8scwiMENA2V3LKB3Z-5nfismV1hcZpofjr3x_msrAj7AY63cdhyuR750xm7VtM4rOuk_TnrQNJmbUFcF2-jhzgqnaMoSuKG7l7Vgfpfmb_eaqjoyr1SVyMBbBD3BHWYtHENNcx5lujJNs4K3Z7Jbgv5E-2vHu-MSkhszjZ966RXQdQAP91STZVbmgWKvc10E4Mt-8txP52lozCMjc2r5CTLkjB7-JGACjVsloY3cRo2GMTUTsHVWKca_PO4fJPABKeqGO9tuNsYbHVWjXSqoX9WQAGx3Ju1nx-ohb8rYkh6Osh_pBDexmAr4vXI__f1HSwdQ0j8AM2_WfzaW0udSKzLBxO2V6N_urIu0iDXCprm0xlYw49Vhf24bJldYXBWKP6sAHCj1RTSJnZGD8YSfyAOPDmfLNYCfkAT_bise8W0sVL4T-GyWh75KTy2MQEjrh2Lk6nZfPizLYz8c5PMl3jf3mcRvbYQ2JrQauDPC1rtrdgjiBF7s3WVx-HT02Y96s-OST9iMd9dobsC91LJ_nJtD7delVuM-7NEe5xl5Q-Ve9735HoBXZZhEWjfX7qdSKyz62KwU4229Uphu8akivJD2lxu_4H1pV5c1mtLgMF5GOvUqbE46x2A_1vm9ROWJ97qXCXhh-hqlldx_GesTmzifKJ66uFOFjkdRL0-OHqMizPAp0fQWcc6X85Wnaz4VyixyGZ5YI61A8cv-ctRNkuc0TQGKobOSQY_nOuqmO9Utvnqnxykv8ySFGTix_2p_anZuoVxQ8SLT9Wu2adca0fVbFUj8WKnCn5pXiAwxJgZstDsdbnCJXhICBNiaE5nDTHm0hsSiogYuvCRDzFCngefCTx3JeUGBkk5xEyQIUWUSvjSQ-6QIEnJUFDhwndI0KEnAavrelwMpefKIZOIGBySyCFxqaRDTjjgkwjhISaIDilnfEiwpGxIGYwBnIzhITwFYOHBVAR7FB57lAG0xB4aUiIwGnKByZDBLEAe8yjMReCpiz3DjSs8mF0QDiMrQJd6YkhdggTMS1yYkyFmCJTUDAWah0RQQoF6ggggQAyQEQZUYM-j3pBSAqKhArANsWACnjBqvkQIaGRGpsIw5GLXSMkVRihUYHcI_ADRnGGQChGceUPGBSEgCk-gIUMSBAJMAjVAPMwBsgVGMAZChhywwXwMyAEVccwNTuCYY-ATnnOKhwwzQOBh4IO5koESgGvKPfiKcAYsES45oAVlGHlLmIgzBDJ1KeIYGBOMDbE0FAHzHOhCxDw2uI0egEYPIMEs4AGWggMDTDLXsAS8Y48jzyjdyAHggWHkAjLX5TCICA8sAAgH7TFsSAfKQNiUGwFR6XkMJsRGBFIKoKxSkAAVuAwZGRGQIJAIeqBMmEkFCA0euCAiUAZIy4WJGSagZMoAiTEEUINHmMHPwIJA8IIdOCX4S-NyjmlOgqV_oEVAOINWRofvjass0vLn63fVh7-My3JavHzx4uHh4XCqynEW6cc40YdBNnkxBTTghs-rsPDcTPTiCP53bP7_7s67OT278E7I9Cb6QC9Pwm_l-3PJ4_LjcXxNbvPA_XxzFHz7Ix__Mr25n87fIfcreX7_Rv7uXf4Wffw4-nZ6N_4ych_I57MgOkpuZsHXyZd36e_n53_8kd3c_sZc8te745tTTcVxdnN8Vo7_Ju_x5G3M3rz5OuPzr79Gf518QfSP2_HJp1_QKD8N8F8_HqV_U3cf4qOL6Ob93979mtzzK__oPry7_5U_fmVfHr9-vCy_uUV6dRRdneDg4-mvN-LB9U4fP96ekLe_3Y_Uxd3Z-3RC_pgXs9nV83v3r19Pb07JQ6Cf83x-_dv7iPHs7Bgl1yQWz7-czf-Wk8f08fITyf9g5Xl0-mV-pz5--e35ZPLmao7S0w9HiXxMx-c38kGdeo_T-a18OGfiy8X8aP4LOVa_P5yrm_ju_G2lmBdLzbyqL0MVtZoWv1Xhrop8YF0SUk9Zp9DF2bEOOAwhzAKOQ6xybeDA36gFHMRgzwafK7nwbPBRjC3APPAaCzDKuRW3EMowsZEy4dhKKhAhmQ19ELxs8GHpUm4zr3SFzbxVTF_DiV76IODb0GdOGlrBua4VHHMhiNpYFcRwz0rOkA3WcKTf7KGQsOIX2UwL2YAyKzaoZ2VW1NzasBAfZGObebHrWc3rmrRpg49iYSM-KBeklVtyyM429EHytgt-kGBt-ECMEiuzgmrNhj4Xcxs4LIiVOUOdK4kVv5xzKzjXal5ChGsjP2bKOyu7ItzO7i3txfWs7A8qfGmXtAS3sheoALEdfTZg5u6kDRsCSlebXCk8YZUrvVaMxL3WAvW9lVFR1BGEoAVc1zvwC3R7VWNo2kHz4X1W6uq7K5Ur5436pnPn-eBSJ2Nol3Mncx5UGg6OUp04IfSP0yQO4PF9s-scvJvdqwK604kzXSz0OmG9epPdA7oynujBSTIrSvjFQPlJloWOysu4KAcqzeK0VNU3E5jLLC4ApE4GZZ6ZuRRA3mc5TG7miAv4AZT4Kn7MoA92dPF1pvNQOdMsN5iDO_P0IS6DsaNBOk4xVmH2YHhe8lr1wl9i_eAUWuXBeFTmrw-CauPEKbMFElXdslkwcuB8y7LJb6Bc71DyqquBfoyx-hzoW63KSzVdrQYY2HerVbjqDGmpytPY7AZWJ2CXDb0B_BWAXHLIoHWCNpKTxc2vV9WizaJhN59Hum79Z4VenDqoVpWrx42Dpwa0OkALBVZlANfKLNS8dD6_v_j4-WxwYwQTxSDO41w_DEZl7Juj3c4b6G3uBp_TGKTpXJy-BAFHYYgCDkT7AcKUBCGUni5XLrSRkqnI41pxyqGjirSQKELIBxiNaBBwjKJBRUklhpeOwIPFjtZLxx1UD6_1V_gsBxcTY1NxWbx08OAkB1FqYNsZTbI77Zwk2QwsInU-F3rA0L-ZNaHFTuPi0oaRRzigbvOrxdKhuV3jfALjc8KZ2YWteXTqQ-GD81ylZVET6BBsjrJNVZw7J7O80I7Zo-gcZpzIcNYWNtkQ9vXR9dkgm4IjVO7zwXy6MZ9OchVBy_jSMQYwuMp1FD--dP4OtNzql-iQCfGP-q5WxcKHtFYy74D8R73GtNxaqUaZJb6KIbwaYF7jMBjNIptfVioiaLCIGi-d4-fwX0NlnLRV9vdS3RYvA2W8-_faW4aLH_XDfzRo_g8qn7vkP5vKqghfqGwgUO9Xz7DxzVpdECIUfLPkfQFYLycaGVSB7zILr83ETjW9ucHK6qPly5stHXqEtLytx6MpxKFkPgWzAPvURonxpACj_EU_QJhq-AzxAkUVJ8j1AiKkcBkOuOcx3_ND4VFfCIp9EREpJKM4iDzJkVS-G4W-jASTLZ8hXlvQxpwfxjqZOOTf1qwvbH11vXGASVOE9V3BJdTDOE60M86ql5IYJ6suGwyegfeAbDdxZiv_Wb-VYsCb2CfqMZ7MgOI4AgXR6qdzq8wJfCeCcKwVBOGzVE_mzjguHX_uzLNZviCqGJxkeT6bgjv0aEN0KONkDATlcWBoB5O91GEMBCyzy5ZGpCbCQzgMVESVjEigo4gSV4YejxT0C8hzhQAdaU-GPrRVxNSsAfIFQtgNVNDSiGyGLi6a6qGDvwe1a__jKAwLx3Wu6kWe2iqL9dfYAQCQT-t7JzYxr6LeqT2vhc_4wqSy-BZS59bEsJfOU_S3AxskkWwDZXVX0alvhJj0aD2cV8PNvdDm6F7ej6uK4KiuCHqhTuI8SIzlfvCT-N4Ye080Rh2G8yWegjjOisJk4H4XRppTRHzhk5ApwQIplQrBXzEk55ART7gqikJJwNElIhL7miPOqS-xDHm4kfYkbdoIGmDW9J46gG-qDfzIXpus1xtpRxQw1VW1wVZdgfuu--Eu98tyEwffZdl08EXnE9CMucNjtk6aUvRkwKSmZsnXA2_ylEbCizARKsSBdCMvoj7xwBeV52rKeCQVM7EyICjSJKD9bidROyqK_njkekaOUNzp9LYcD56J6vcNmG5DXXurjcbW0HyjQgHnWcD0WGpbxJdH5xcnA6g3biGfgSP9OyT_4r8KZxQnRvt1IQLJ70bl4YbEEdUaRRHWIFvGUEgiyDCR63PGWcBwFFAvRCHoJKQsopIqRnwPKRqxwPcj4bckzmh3uUZI257N5T0HL0qxetsWAjzU69p5W8d7ldbxH8ZNZmlVXlcFVtEurnRdXF3riTm-uQQBw4Lqrkd0tMM6r0ByII8TaGWmCtQ4AvpWQnyrZr7OWzUuVLQBgvysmRdwjXylmVQoolHgBoHLvUBryAm-CJV0fYUE8ZRLIByAt2OEZTtfY4QaFRRfV1A3UEFdPz83__bmDwT1DRZb9lm9eUKb856OOFzkVxPGiqoDAPOVdZiGjN5pvqRVT9UXxaowUF82XBYAK_hnHTR0i9_tstwjYAji9SyZjmcNcz2pVN0UPJaB50dIQYxFIYaUSyIkqUeQgmbCj-CXCHQilNlki6TvaxH6ITFxFoomqtrWylmrcl2LmLLu7uIkSxenaMGl82yWrlqMBf-XC_4XPUbDeOs7s52dwdJ4FyA7jZd1hVaV5yaWjlRyX52hHJxBSZNCmDme5bdQn5dNCRqnlj4hkKJoCAWOIFpS05y5Ero0V2DFwKmE0lwExPV46IWKEE9S7AlJlGq3Z7y79r8Bu71pV_8bRenKcpq386A_h2LAcdF2UzbAYLG5KVbrtFRfuQXb_TqDEFzd7gWrZu3ATSul1NYLYZxumWjDfr3KIVavcmh6RbcqeIcqGucGButjA03xU-qKELEAQ2EZEfOKH6aIomFAkfJCrnzuRQQxjsGrmeuZ3SLsCo2QkjCOhwMI4UmWh46ho53tmhbMW9mOrBmtT1wUTrG4BGJi7W_GuUdBNiudT-aEZOGMFZRPhHWo4RlFW1KsClduHmNah5RF6WGEvyjZW-m2UUs8I7hf8HVLbfJADP7xEJdjp3VswfgK5Ith_VU7Zi2ca61h5lpGKNml2LtZYs5R5booBjfzfFJAGtfOuZqlZQIm31SxK3wUhoGIRADpwaOY-AHjMpSImhJQIea7XPraxT5SEMp4GCDtcSUicD0cqcFbQAqxukvDK29rONt2inC9jRThyrZjmOrEtlQ0C [...]

2021-05-13 03:13 UTC, Wires77 reviewed
This might be worth reworking to work like the mana config one, otherwise simply adding the flag to CalcPerform would be better than making them check a config box

2021-05-13 11:54 UTC, pundm commented
We had a talk about the condition/flag in CalcPerform, but i haven't found out how to access if a skill has LifeCost > 1
Can you point me to the 'mana config' example?

2021-05-22 04:44 UTC, Wires77 commented
Oh, sorry, must've forgot to respond to this.  I just meant the config option just below the one you added, which gives a value for mana spent recently instead of a checkbox for "Have you spent mana recently".  I'm just thinking ahead for if they add more skills/mods that require a certain amount of life spent.

2021-05-22 09:10 UTC, pundm commented
![Path_of_Building_BARL8B1w01](https://user-images.githubusercontent.com/54453318/119220962-499d6780-baed-11eb-88fe-aa750919aff0.png)
![Path_of_Building_O65A1kYsQe](https://user-images.githubusercontent.com/54453318/119220964-4b672b00-baed-11eb-8b88-ffd5e1854999.png)

It's working, but I'm not 100% on **ifCond = "SpentLifeRecently"**. It works but all the other countboxes seem to use **ifMult = ""** which didn't work for me, probably because in ModParser it uses **type = "Condition"** instead of **type = "MultiplierThreshold"**

There should be push-access on this PR for maintainers, so please someone with more knowledge fix this if needed or please tell me what i need to do. Ty!

2021-05-25 15:28 UTC, Wires77 requested changes
These were the changes I thought you'd have to make to get that working better.  I also changed the variable name to better match what it's representing

2021-05-25 15:28 UTC, Wires77 commented on src/Modules/ModParser.lua
> +	["if you[' ]h?a?ve spent life recently"] = { tag = { type = "Condition", var = "SpentLifeRecently" } },
```suggestion
	["if you[' ]h?a?ve spent life recently"] = { tag = { type = "MultiplierThreshold", var = "LifeSpentRecently", threshold = 1 } },
```

2021-05-25 15:28 UTC, Wires77 commented on src/Modules/ConfigOptions.lua
> +	end },
```suggestion
	{ var = "multiplierLifeSpentRecently", type = "count", label = "# of Life spent Recently:", ifMult = "LifeSpentRecently", apply = function(val, modList, enemyModList)
		modList:NewMod("Multiplier:LifeSpentRecently", "BASE", val, "Config", { type = "Condition", var = "Combat" })
	end },
```

2021-05-27 05:35 UTC, Wires77 approved these changes

2021-07-18 00:50 UTC, merged