Fix support for Petrified Blood
PathOfBuildingCommunity/PathOfBuilding pull request #2806
Opened 2021-05-19 17:02 UTC by Wires77

The breakdown for the added life cost isn't in there, but this seems to work.  There might be a better way to implement this, just hacked it together quick over lunch.

2021-06-04 21:59 UTC, ppoelzl approved these changes
It's alright as it is.

2021-07-06 14:14 UTC, PJacek requested changes
This check seems to fail https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/778b4a588d7d0364e07d1535f9cb6a8d780234c4/src/Modules/CalcOffence.lua#L1006 and displays the breakdown for equal base and final cost. If you change the output formatting to float you can see that the values are actually different
![cost](https://user-images.githubusercontent.com/18018499/124596014-08290780-de62-11eb-99fb-4595bf6b00ea.png)
According to my testing (6 base mana cost with 1.76 multiplier results in 4 life cost not 3) the value coming from conversion is used in calculations without rounding so we should probably display fractions.

For the breakdown you can just add `ManaCostAsLifeCost` to the listed mods

The aura totem costs weren't working perfectly before but now are completely broken. Moving some of the calculations to earlier pass misses the base cost added by summoning and the code refactoring both duplicates flat reservation as percent cost and misses percent reservation.
Anyway, I don't think anyone uses this interaction so it can stay like that. I can fix it later.

2021-07-17 23:54 UTC, ppoelzl commented on src/Modules/CalcOffence.lua
> +						s_format("%d"..(percent and "%%" or "").." ^8(base "..name.." cost)", baseCost)
Shouldn't this round up to the next integer then? As you can't spend exactly 2.4 life anyways.

2021-07-18 06:48 UTC, PJacek commented on src/Modules/CalcOffence.lua
> +						s_format("%d"..(percent and "%%" or "").." ^8(base "..name.." cost)", baseCost)
The math is a bit complicated
https://github.com/PathOfBuildingCommunity/PathOfBuilding/blob/778b4a588d7d0364e07d1535f9cb6a8d780234c4/src/Modules/CalcOffence.lua#L994-L997
My point is that the base cost from conversion seems to allow fractions and the calculation uses fractions so we could display it like that

2021-07-21 05:09 UTC, merged