Update new gems
PathOfBuildingCommunity/PathOfBuilding pull request #2999
Opened 2021-07-25 01:09 UTC by LocalIdentity

Voltaxic Burst
Rage Vortex
Spectral Helix
Battlemage's Cry - Partial Support
Earthbreaker - Partial Support
Absolution
Manabond

2021-07-25 15:24 UTC, PJacek requested changes
You might want to check indentation. There is a few places where you used spaces instead of tabs

2021-07-26 00:53 UTC, ppoelzl commented on src/Data/Skills/act_dex.lua
> +			mod("ColdMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 2, 5, 6, 8} }),
```suggestion
			mod("ColdMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 2, 5, 6, 8 } }),
```

2021-07-26 00:53 UTC, ppoelzl commented on src/Data/Skills/act_dex.lua
> +			mod("LightningMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 3, 5, 7, 8} }),
```suggestion
			mod("LightningMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 3, 5, 7, 8 } }),
```

2021-07-26 01:56 UTC, ppoelzl requested changes

2021-07-26 01:56 UTC, ppoelzl commented on src/Data/Skills/act_int.lua
> +			mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable
```suggestion
			mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable = true }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Data/Skills/act_int.lua
> +			mod("MinionModifier", "LIST", { mod = mod("Life", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable =
```suggestion
			mod("MinionModifier", "LIST", { mod = mod("Life", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable = true }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Data/Skills/sup_str.lua
> +			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "ActorCondition", actor = "enemy", var = "LowLife"})
```suggestion
			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "ActorCondition", actor = "enemy", var = "LowLife" })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_dex.txt
> +			mod("ColdMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 2, 5, 6, 8} }),
```suggestion
			mod("ColdMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 2, 5, 6, 8 } }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_dex.txt
> +			mod("LightningMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 3, 5, 7, 8} }),
```suggestion
			mod("LightningMax", "BASE", nil, 0, 0, { type = "SkillPart", skillPartList = { 3, 5, 7, 8 } }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_dex.txt
> +			mod("Damage", "MORE", nil, 0, KeywordFlag.Ignite, { type = "SkillPart", skillPartList = { 4, 6, 7, 8} }),
```suggestion
			mod("Damage", "MORE", nil, 0, KeywordFlag.Ignite, { type = "SkillPart", skillPartList = { 4, 6, 7, 8 } }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "SkillPart", skillPart = 1 } )
```suggestion
			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "SkillPart", skillPart = 1 })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +			mod("AreaOfEffect", "MORE", nil, 0, 0, { type = "SkillPart", skillPart = 1 } )
```suggestion
			mod("AreaOfEffect", "MORE", nil, 0, 0, { type = "SkillPart", skillPart = 1 })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Data/Skills/act_int.lua
> +			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "SkillPart", skillPart = 1 } )
```suggestion
			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "SkillPart", skillPart = 1 })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Data/Skills/act_int.lua
> +			mod("AreaOfEffect", "MORE", nil, 0, 0, { type = "SkillPart", skillPart = 1 } )
```suggestion
			mod("AreaOfEffect", "MORE", nil, 0, 0, { type = "SkillPart", skillPart = 1 })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +			mod("Multiplier:ManaBondUnreservedMana", "BASE", nil, 0, 0, { type = "PerStat", stat = "ManaUnreserved" }),
```suggestion
			mod("Multiplier:ManabondUnreservedMana", "BASE", nil, 0, 0, { type = "PerStat", stat = "ManaUnreserved" }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +#baseMod mod("LightningMax", "BASE", 1, 0, 0, { type = "Multiplier", var = "ManaBondUnreservedMana" })
```suggestion
#baseMod mod("LightningMin", "BASE", 1, 0, 0, { type = "Multiplier", var = "ManabondUnreservedMana" })
#baseMod mod("LightningMax", "BASE", 1, 0, 0, { type = "Multiplier", var = "ManabondUnreservedMana" })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +			mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable
```suggestion
			mod("MinionModifier", "LIST", { mod = mod("Damage", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable = true }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/act_int.txt
> +			mod("MinionModifier", "LIST", { mod = mod("Life", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable =
```suggestion
			mod("MinionModifier", "LIST", { mod = mod("Life", "MORE", nil) }, 0, 0, { type = "SkillName", skillName = "Summon Reaper", neg = true }, { type = "GlobalEffect", effectType = "Buff", unscalable = true }),
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Export/Skills/sup_str.txt
> +			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "ActorCondition", actor = "enemy", var = "LowLife"})
```suggestion
			mod("Damage", "MORE", nil, 0, bit.bor(KeywordFlag.Hit, KeywordFlag.Ailment), { type = "ActorCondition", actor = "enemy", var = "LowLife" })
```

2021-07-26 01:56 UTC, ppoelzl commented on src/Modules/CalcPerform.lua
> +			modDB.multipliers["MaxRageVortexSacrifice"] = output.MaximumRage / 4
Poedb says that you can sacrifice 20% of rage, not 25%: https://poedb.tw/us/Rage_Vortex Also, shouldn't this just be a normal multiplier mod as well, or is this not possible due to the evaluation order?

2021-07-26 01:56 UTC, ppoelzl commented on src/Modules/CalcPerform.lua
> +				local battlemageSpellToAttackMax = m_floor(150 * buff_inc)
Consider refactoring this magic number to `data.misc`.

2021-07-26 01:56 UTC, ppoelzl commented on src/Modules/CalcPerform.lua
> +				local battlemageCritChanceMax = m_floor(30 * buff_inc)
Consider refactoring this magic number to `data.misc`.

2021-07-26 02:01 UTC, ppoelzl commented on src/Modules/CalcPerform.lua
> +			modDB.multipliers["MaxRageVortexSacrifice"] = output.MaximumRage / 4
Update: This is support for helmet enchantment. Thanks, LI.

2021-07-26 02:20 UTC, merged

2021-07-26 05:39 UTC, livejamie commented
Thanks for all your hard work guys! Looking forward to Forbidden Rite. :)