Add support for Energy Blade
PathOfBuildingCommunity/PathOfBuilding pull request #3580
Opened 2021-10-23 16:11 UTC by PJacek

This was a bit complicated because Energy Blade actually replaces weapons (the bases exist in data, not doing some magic like "treat x stat as y"). Some skills require the use of certain weapon types, so items need to be processed before skills. Energy Blade needs to know if it's active when replacing weapons, so skills need to be processed before items. This creates circular dependency, which I think can only be solved with a config option (processed at the very start).
- Added the special bases - they have modified names because both are called "Energy Blade" in GGPK and we export all bases into the same `itemBases` table. They are not available for crafting
- Used weapons are completely replaced with Energy Blade(s)
  - Requirements of the original weapon are used - the swap happens later and energy blades have no requirements
  - Any mods present on original weapon are discarded
  - Weapon type restrictions function correctly - Close Combat can be used, mods requiring Sword attacks apply, etc.
- Crit chance from quality applies to base crit as if it was a local mod
- More damage bonus when using a two handed weapon applies to the base damage
- Battlemage works correctly
- Weapon restrictions can now be applied to non-attack skills. This disables the skill (and buff) if no usable weapon is equipped
### Sample build
```
https://pastebin.com/w5x1x15n
```
### Screenshots
Energy Blade buff:
![image](https://user-images.githubusercontent.com/18018499/138563338-66ef107d-83fd-4727-ba67-896826cd0674.png)
Concentrated Path supported by Close Combat usable with a staff equipped:
![image](https://user-images.githubusercontent.com/18018499/138562826-3b862e99-c9aa-4383-be1e-3fe47300b2c7.png)
Base crit increased by quality and sword mods applying:
![image](https://user-images.githubusercontent.com/18018499/138562869-f9bf3c31-79fa-4f0d-9225-e3fc77a81642.png)
Skill disabled when using a bow or unarmed:
![image](https://user-images.githubusercontent.com/18018499/138562981-40e11441-9358-426d-bc6c-c94e6cb000ae.png)
Requirements from the original weapon apply but the mods don't:
![image](https://user-images.githubusercontent.com/18018499/138563059-dfcb33ae-37d8-4394-bb9a-270f9a073da3.png)
Battlemage:
![image](https://user-images.githubusercontent.com/18018499/138563094-5d1bad2b-53d1-48c0-8f68-027be518ed41.png)

2021-11-01 14:23 UTC, robinerd commented
Hi! Thanks for adding this support! I'm currently running a build with energy blade and wanted to try it out in PoB. Found this commit but have never looked at the source code of PoB before. Also want to point out some issues/findings I came across.

I managed to setup the development installation, took the dev branch and merged in the branch from your repo too. I also exported the game data with the .dat tool thingy.

The first issue I had was that I wasn't getting the energy blade weapon, but then I found it's since when I import my character it doesn't import any weapon on my mainhand, and so, I won't be able to get the energy blade buff since that gem requires a weapon.
If I manually edit my build in PoB to equip any 1H weapon, I get the buff and all works.

My second issue was that it also doesn't import any of the gems in my main hand. I suspect that something needs to be changed in the import code to correctly import my character if energy blade is turned on in-game.

NOTE: it could also just be something I haven't setup properly in the dev version, so please ignore me if that's the case.

Anyway as a workaround I can just manually add my last gem and add any 1H weapon, and I will be able to test things with my build. Cheers and thanks again!

2022-01-11 06:56 UTC, Wires77 commented on src/Modules/CalcSetup.lua
> +				elseif (slotName == "Weapon 1" or slotName == "Weapon 2") and modDB:Flag(nil, "Condition:EnergyBladeActive") then
Would it not be easier to just use item:ParseRaw(```
test
Energy Blade One Handed
Quality: 20
Sockets: G-G-G
Implicits: 1```)

and add the raw implicit text from there?

2022-01-11 07:16 UTC, Wires77 requested changes
Looks like the import bug is because the sword imported looks like this:
```
Rarity: Magic
Superior Energy Blade
--------
Item Level: 60
--------
One Handed Sword
Elemental Damage: 56-1120
Critical Strike Chance: 8.54%
Attacks per Second: 1.70
Weapon Range: 11
--------
Requirements:
Level: 70
Str: 155
Dex: 116
--------
Sockets: R-R-G
--------
Adds 56 to 1120 Lightning Damage (implicit)
--------
22% increased Critical Strike Chance
```

That base type doesn't exist (due to the renaming you had to do).  If we can fix that, or at least import some dummy weapon when we see the "Energy Blade" base, this should be good

2022-01-13 16:23 UTC, Wires77 commented on src/Classes/ImportTab.lua
>  		item.name = itemLib.sanitiseItemText(itemData.typeLine)
Looks like this ends up being "Superior Energy Blade" if there's quality on the gem.  We could use `itemData.baseType` instead, but I'm not sure what else that would affect, as far as the typeLine goes

2022-01-14 02:43 UTC, Wires77 approved these changes

2022-01-14 02:43 UTC, merged