QOL: Allow Modifiers to be shown by prefix or suffix
PathOfBuildingCommunity/PathOfBuilding pull request #3886
Opened 2022-01-12 08:39 UTC by pHiney

Partial fix of [Crafting Bench modifiers do not respect any of the crafting rules](https://feathub.com/LocalIdentity/PathOfBuilding/+41) . The rest of the request appears to have been solved by adding the '(Prefix) and '(Suffix)' to the modifier list. This should complete the request.

### Description of the problem being solved:
Crafting Modifiers prefix or suffix are joined together.

### Steps taken to verify a working solution:
- Open a build. 
- Edit an item
- Select "Add Modifier ..."
- Choose a Source and Modifier type
- Choose you Modifiers and select Add

### **Doesn't change current functionality, only the presentation of the modifiers**

### Before screenshot:
![image](https://user-images.githubusercontent.com/4302241/149090244-59a4452a-5a35-4f14-a6c5-2274c3416d05.png)

### After screenshot:
The default is still to display all Modifiers
![image](https://user-images.githubusercontent.com/4302241/149090580-3fcaf5dc-4aeb-4dda-8703-e506c6a2c329.png)
(edited picture, you can't have both dropdowns open together)

Selecting prefixes shows only prefixes, suffixes does what you think. The '(Prefix) and '(Suffix) is removed as they are redundant.
![image](https://user-images.githubusercontent.com/4302241/149090750-5749ac90-b7ea-4235-9f18-12cdeb67e3c1.png)
![image](https://user-images.githubusercontent.com/4302241/149092232-da8289a8-ef35-47b3-874b-10ce8eb5653b.png)

The Modifier DropDown disappears when selecting a Source of 'Prefix', 'Suffix', or 'Custom' - and will reappear when other sources are selected.
![image](https://user-images.githubusercontent.com/4302241/149091305-957d2e44-e049-4c3e-9973-bb2778f48590.png)
![image](https://user-images.githubusercontent.com/4302241/149091372-eca7cf48-ab58-4e90-9250-e5a27c01bb6d.png)

2022-01-12 08:42 UTC, pHiney commented
Need to review names of variables

I think the 'local function addModifier()' should be moved up to under buildMods so as to not have functions in the middle of code.

pH

2022-01-17 21:41 UTC, Wires77 requested changes
Thanks for the contribution, but I'm not certain this change is necessary, as the feature request you linked to is pretty old at this point and I haven't seen much need for additional filtering outside of what is available.  It seems like a lot extra code complexity for not a whole lot of gain.  I had some code comments before coming to this conclusion, so I'll include them still, but overall I'm inclined to close this.

2022-01-17 21:41 UTC, Wires77 commented on src/Classes/ItemsTab.lua
> +					local currMod = {
You don't need the big if statement and creation of a local table here.  You can just add a ternary to the statement that was previously there, i.e.
```lua
t_insert(modList, {
	label =  table.concat(mod, "/") .. currentModId == "MODIFIERS" and " (" .. mod.type .. ")" or "",
```

2022-01-17 21:41 UTC, Wires77 commented on src/Classes/ItemsTab.lua
> +		buildMods()
You really don't need to change the method signature everywhere just to enable this call.  Just grab the sourceId from the other control and add the modId as a second parameter:

```suggestion
		buildMods(controls.source.list[controls.source.selIndex].sourceId, value.modId)
```

2022-02-01 01:34 UTC, closed without merging