Get rid of "Done" button on character import
PathOfBuildingCommunity/PathOfBuilding pull request #3898
Opened 2022-01-16 23:38 UTC by raylu

This moves the account history list functionality to "Start".

### Description of the problem being solved:

After walking a few dozen newbies through PoB-ing their character, this is the main point of confusion. Almost all of them see the "Passive Ttree and Jewels", "Items and Skills", and "Done" buttons and click "Done". As far as I'm concerned, this button is a trap.

### Steps taken to verify a working solution:
- Tried importing a character
- Made a new build and confirmed my account was in the account history

### Before screenshot:
![image](https://user-images.githubusercontent.com/90059/149682801-201a5c9a-1cef-40d0-896d-5402f5c7159d.png)

### After screenshot:
![image](https://user-images.githubusercontent.com/90059/149682808-8b04e096-9d18-4b6e-bb5c-370225bd3a91.png)

2022-01-17 14:34 UTC, Lothrik commented
That button does serve a purpose, though. Changing the label from "Done" to "Cancel" might have the same effect, or possibly adding a confirmation prompt "Are you sure? You haven't imported anything yet." if the user didn't actually import anything.

2022-01-17 20:00 UTC, Wires77 requested changes
This change makes it impossible to switch accounts once you've selected one without restarting PoB.  I'd suggest just changing the button text to "Choose a different account"

2022-01-17 23:36 UTC, raylu commented
I went with "Cancel". Let me know if you prefer "Choose a different account" still.

2022-01-19 22:13 UTC, Wires77 reviewed
Do we need to move the account history logic, now that the button exists again?  It seems the only benefit is to save the history list when you hit start vs. when you hit cancel.

Also, historyList is a global variable, so it doesn't need to be passed as a parameter

2022-01-19 22:42 UTC, raylu commented
> Do we need to move the account history logic, now that the button exists again? It seems the only benefit is to save the history list when you hit start vs. when you hit cancel.

I'm happy to undo my account history logic move if you want. It seemed weird to me to have a button labelled "Cancel" save the account name.

> Also, historyList is a global variable, so it doesn't need to be passed as a parameter

whoops, fixed

2022-01-19 22:44 UTC, Wires77 approved these changes
> I'm happy to undo my account history logic move if you want. It seemed weird to me to have a button labelled "Cancel" save the account name (or do anything, really).

That's a good point, so this looks good now, thanks

2022-01-19 22:44 UTC, merged