Fix incorrect curse priority
PathOfBuildingCommunity/PathOfBuilding pull request #3930
Opened 2022-01-20 21:31 UTC by Lothrik

Fixes #2808.

### Description of the problem being solved:
Curse on Hit from corruption implicits are always applied after Curse On Hit Support gems, and trigger mark when you hit mods on rings. Curses from rings appear to override curses from gloves. The earliest alphabetically-named curse has highest priority, up to the curse limit. Curses are applied in alphabetical order according to their internal name. Despair's internal name is Vulnerability and Vulnerability's internal name is NewVulnerability.

TL;DR:
- If you have Curse on Hit gloves: the curse from your gloves should always override Hextouch + Elemental Weakness.
- If you have a Frostbite on Hit ring, a Vulnerability on Hit ring, and Elemental Weakness on Hit gloves: Frostbite should override Vulnerability, and Vulnerability should override Elemental Weakness.
- If you have Vulnerability + Elemental Weakness on Hit gloves, Elemental Weakness should override Vulnerability.

Almost everything I just listed above PoB gets wrong in 2.13.0, as it makes no attempt to prioritize curses alphabetically, prioritize curse on hit corruptions over anything, or prioritize ring curse on hit effects over glove curse on hit effects.

I'm not 100% confident about how I'm handling triggered Marks. The wiki claims they're prioritized below implicit Curse on Hit gloves, which makes sense.. sort of.. given that the trigger effect has a cooldown, but I'm suspicious about the exact mechanics involved.

### Link to a build that showcases this PR:
https://pastebin.com/N4eu1SBZ

2022-01-26 18:23 UTC, Wires77 requested changes
In hindsight, I should've made the changes as one suggestion, sorry if it's hard to read.  In general, we use `stringVar:match(pattern)` instead of `string.match(stringVar, pattern)` for string functions and `nil` is falsy, so we can use `if var then` vs. `if var ~= nil then`

As a future PR, we might be able to construct the priority table from the export scripts, but this works for now.  I'd like to see a reasonable fallback value if the curse isn't found, though

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +						priority = determineCursePriority(buff.name, activeSkill.socketGroup.slot, activeSkill.socketGroup.source) + (activeSkill.skillTypes[SkillType.Aura] and 30000 or 10000),
Can we change these magic numbers to constants or at least calculate them as part of the `determineCursePriority` function?

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +	if string.match(curseName, "'s Mark") ~= nil then
style

```suggestion
	if curseName:match("'s Mark") then
```

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +	local sourcePriority = source ~= nil and 200 or 100
```suggestion
	local sourcePriority = source and 200 or 100
```

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +	elseif string.match(slot or "", "Ring ") ~= nil then
style

```suggestion
	elseif slot:match("Ring %d") then
```

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +	local basePriority = data.cursePriority[curseName]
```suggestion
        slot = slot or ""
	local basePriority = data.cursePriority[curseName]
```

2022-01-26 18:23 UTC, Wires77 commented on src/Modules/CalcPerform.lua
> +						priority = determineCursePriority(buff.name, nil, nil) + 20000,
```suggestion
						priority = determineCursePriority(buff.name) + 20000,
```

2022-01-27 00:44 UTC, Lothrik commented
All of that should be fixed now, plus some other bugs I noticed while going over this again.

2022-01-31 08:22 UTC, Wires77 approved these changes
You had left/right swapped, but this looks good now

2022-01-31 08:22 UTC, Wires77 commented on src/Modules/Data.lua
> +	["RightRingSlotHexType"] = 6000,
```suggestion
	["RightRingSlotMarkType"] = 2000,
	["LeftRingSlotMarkType"] = 3000,
	["AnySlotHexType"] = 4000,
	["RightRingSlotHexType"] = 5000,
	["LeftRingSlotHexType"] = 6000,
```

2022-01-31 08:22 UTC, merged