Get maximum animated weapon from gem level instead of configuration
PathOfBuildingCommunity/PathOfBuilding pull request #3935
Opened 2022-01-21 15:50 UTC by Wires77

Fixes #543 .

### Description of the problem being solved:

Animate weapon in the configuration tab had a maximum of 50 instead of depending on the gem level.  Since most people will only ever have maximum animated weapons, I've removed the config value
### Steps taken to verify a working solution:
- Tested with chains of command, as that's the only thing that cares about the number of animated weapons

### Link to a build that showcases this PR:

```bash
eNrtPWtz2siyn5dfoXLV3spWwNboLd_knMJvJ34F_NjkS0qgMcgWEtYDG2_5v5-eGQkkkMSAnWTPHjZVXpC6e3p6-j0j8eHfTwNXGOEgdHzv4wbaFDcE7HV92_F6HzeuLg8axsa__1X7cGFF_fPbndhxyZ1_1X77QD8LLh5h9-OGCWiRFfRwdJ2Skr_DtaHlRX3se6fWnR8c-vbHjTPfwxtCx_JsJ0q_dV0rDM-sAf64ceNE3f6GYIVd7Nm70-tnuBv4A8vr4mBDGFiO1_a79zg6DPx4CMNvCCMHP576NoAen16cty4zYztedmzg_bcPF641xkE7siIhhD8fN5ogAquHj5wISFluDHTEja1K2D1rAH8Xg7eHGNsTMLRpqD8T8iLA-7e3uBs5I7wbONFunwhxMdfLwp7GbuQMXYesz4StUq6O5ogjsZT8pR9Z7t5FezEjy0L6HKsNGtnfcUHcXHQJ9HHPcyLMDX7hO6HvLcU1F_CuP-g4HiffKXBz1OMB9l3bf_SmkJuippVBn1qeteuHHKI-cW4xH-R-mw-uBRbKB0m4vMABuJ2In9mlENpRxjTkUtNo4YcspGmWAe7hpwmUXkUuC4jUUshjbzoJyZQrCGYhKwju4ZEfQSzgk-UEStYUs8LvdbcJ9LHXzbCgVxG-8gIc4mCUcZhVQ-RRkhXmcVMEsYV72MusMtqEoaoQTjDu9g8hnrWsCPNp6VQ1NKNSTgQ4KyfJqCJbIKYGMjQ-lFkxNZC5KSHF0DVRlkW1cuC8zKqZXFJcN1ZgczgTDwe9cbvvYDcTU5GoVEo3i5WVssw1Tn7SXChLzn1_ZIVZ45PE6ukw8OxMyrUQQzwEBBvzZgjLY1wE_h3JWtzl0JrBwI-DjB_T5cppM_iclZSz1B-HThcCME38WtiOuzn3JpcONcnATv0RHoCh0PwN0tVMroRKPdKOC7kurwCAsusuhdGMIqt7v-fbPbzUIMtjtOPhEDwG0TNevAMnAEmHTibANiR1MfQ55Oi71pAnlyHGyDvAFJp7gBOn1488KJr4R5lB4Z9L3_LD2WFUiQOce4iD2OVLsNv3Th4ysjou3hbEJ0mTRVsyy83MfwRm-qSaDDn8RAb61JomOqW2eBBg73nMTT8HzjXAvmfHAdFu7jFmMYqGgSoWzGZhFaoipCuboiEqk7xjDjNfPKqbyNDLQOcKKklTFdncNFVV1jR9AV5BeTUHWVhecY5SXGxxIs-XXZoqyptI1k1pAU5e5EgWRW1T0lVDqWJ0fjxZBiuQN1XRgExpUsGXyjLHqq5ogKlKuiGJRhlmUQXIOWguI0eipGhVkPlsRld0kL5RhVCcy0iiAmljGV5hmiYhw-RBKM63KlGq8q0PW7T9RT4dD4Z-ENGLu5bbDSnhY28YR4JHW1dh339kA20IHaicseWBNwxinDCRgyVe87sXDzqkj8L-D_IvgBw4Yfd7J769JU2vDWA_oB27_YOD_d3L4-v9BKWNaY4idH3XtYYhtj9u3FpuCBiOnTjpNuRm3YgL_siJEuXngYbsuxs44AB5gImz4GKZOi8eSNKV4gKEFbRczC-wy_EQE50JeWWWJDs80NQVckEyf8I3Qeoj-ZYBd60xF-TEPLig913cdFyS-vJJ7RTUm2XNfPCQxAZOJ444tY26Ny4-SMHNNcGsd-K0Dj7ApKThYiKp-XhgkzyRTymhnOBetj18i0HdOc2eupNL6x57iWNNnegHamuhEIJ3PcSDcGcMYeyAiHcmsOUAEs8q2PjWil1y_UtsuU40Jp47c_WE7VtAsScQ_0wqE0aGGHcIQj85YXeabpRQIGOkvLOZEQbpZkSTFnf0O2WfuGzB8bpubONjL8mZJ_N2rQ4Ze0Pokd2LXT_2IPJ4jkt2XkiSbKeTCF2fJA_YGoL8pI3ZocgohJHfPgBrCe6h63csV5qMRQMKiz7HER60cZQwKOXuzbCeuZNcbHrOAMKgndbX7lR-2YHRhHVC4dieIKZ4s2PODpcwSfl7YHI_pm6JLhyIDA_I91McWbYVWVsEPtwiS7NF6cGnmREfMus_I98uEz1wQGIq6QdM-BUOY7BPx_Jy3M3JYWuR_LnllGggG4eaUEjWOWJl8rKimKjzKbaiNGVaUhIEVcg6tLefJ8syV5_cPBHuyVFUIRMHmP78HMNewZC5BbzjWsTNuW6xYCnchRUwgXCY0zw9XhlPMf9ZEt7D4dBygjeS73XsQupgdRxCamkZp7z8syR84OKwfw7pHylqVg4ExVR4JUuxhQn6zxcwi_47vj0W0lj2I2WeuNWmbWObdgbTNsfK7rmUVH4JEkYLgzGhIFASQrbwfNNIRA4ukPL5_lWhqIAKdyzK4P6ohOK1a1lIZslg-6NWcA9T50m7NCtP8Npx8aX_5Hjh0tMjqEKC--aTo8rPtmjCV0yvkAzvBEn7knpBmGXc7b_9JK99x4ZK2xnGrsW21FZfxzJS3KsJBIQcha0liqyZKLBsmcRqvSXKJPTaMikdccUyqYDhaZGU3ORVF23FEHXhxuEbhqkcOW55PJIWBgSrspD1j8nNLmLPCfsDetpjRdUrIMEr5wzqP0usR1a4SvxKJJrH5hUmw_oJcgwhe-2So7nA-ba0fUXa0TYQEvYCbA3qwm4ckaO-1Q0w9KoFUBctwL43GhfLf0mpUkJvHiIPwbsEfpitEVesOyeOr4Ak7xyzqDnX344HAx_8YAvWDAc_XbfQNnheyMME_1bY9QcDy7PrQhuuRO5YoLdg6B9Var11rzWNrcsmEWnrculkQnoT_Z_toP4fcBH-f_imqcK6nF2Xs-tydl3OrsvZH1DOrsuxf2ROUtyaQMaPzirQOqtYZxXrrGKdVayzinVWsc4q3iir0LabsZsGwath4ISgenXh3Bs_Cc1B7OKoJKNIb67eS0O_opf2C7be36Tv-D_Q33ubQzXUjMhzSJfOADfjwFq5GV5BijsYW8C47-LJse03mWOz2wVmuuOmZ5PD6eGrZnkR4K4TruK8p5gzlpV8oqdvLwOMBYvpPMVCyaFX-JJ9PQdhUyYWEkY4GCdHtj9u_KUgBal1TZEN9FL_S1ZUVaoroqjL8A1JsgHfdE2R4BvASVId6YZKvkmSqYt1RdNkjdwzJFOsSyJS5ReYgm-Ts7kSwEt12dSRXNcVRakjE4lyXYWPel0GTKUuychQ64oha1Jd0iW4C_zoUt3UVBEwDWTUkawjBUB0ZNYlTTFQXUamjABcU826qitAXDYAThFVQtaE6ahIRXpdMSVVqesa3FQpQaTCvOCypgI6MlVCHHiCWQBjcF0EvhBSJPisSwCjazCyLCu6WYdPOoxsIF2rI0OGkRVF1oCkacrAhSJpOvyFoSVdFg2QoCYDA0xiqgbsIjI5yQRRSKosS3VVVWDmmgj_p5OTgZQmwxUVASndMIE5TYQpg2hBTpqhaQCtA7eqZGp1Jn4kijKRh6GrdVkxDDpFBQA1IlUJ_geYEgBqsApwWRVB5qoKDFFmgbokguQ1HQFDhkSkTR44qjM1AG5Fra4Aal1WCUUkgojqpmxo8IcMz_QDIVh7mAlIT5GRDDORReAclkIx60y_FFgPlcgc5A_aBNIGIQIMDKeBiBUZBpJlXYUxFFOG6emmBHfJ7CQYD4H8TTIUrBEspi5JVAJEZzQE7GoiWW5ZMwBH12XCKRA0TAUmJAIOiFInIpJEkCVIWAUu4DOQBd0G1kHT6lSFN4QI7CnzbhykJa-9YfbDXMy-TfbFzoiWJ07nqnVCP_zWj6JhuL219fj4uDm0or5_i58go97s-oOtIZABM21QP9MgA2014b-d3umeffP5cDDetw_2H27vnobWfef5wbo_d5q7N-OB4qP7QL34Jh8YsfR4cjAwuvJeZ3i_d_HporszOOrdDZt3Qf_x9uz66e78KHrWvrvjcTf-dGqP_JMjY6dxfbyP5eCqf6aYF_pB234IPmmmf3ds7j22n3elA8c8c0z9-KHRvho_f_cNLPW-ffp60feNfvvxpuN7J_J4z9lvak993x4-PA28ked_7wXfds3zi2tHsc7Pzx7O48Fh4-hwvN-WTr61H75--uzfD-52sH_eCXta3zyNDr9cW0dH4ZF9jW6Ddku50qTjr7s9M9RuDsVvO017_HR7jAPp-dbp3YmWGZ-G1sOwddXd050T8fPFcKcvi1-_-0fjVmsYag3N8HvNw1Zn7JwGX8ObzkPX-dpR4r7_-OcoMv2ufR7DPbpAW-kKfWAvJApTlwpucuovIydyIXHzu92NWd-JfonvRDK4zRIPyrwG0-l5D0rdHvOdzKVkvSZze8xjJj51zm9Sj5n1m2CxupH4Tep22TSYlZV4Terecl6TOdmMUTKzzbrNxISnblOWFGAr6zdBMChxAcxtskBC3Sbzjxm3CUKQ0oCDdBG8HA0YzKVk3Sb1N9R3Mv-T9ZqJS6TeNOM1Mz6SeS7mdZmPS7wm9XGzXhNmQ7y7LppaodckPpXpF_OaWffM_DDzmsybM98Jq2ooSThgMY0FiKzbZIGM-U0Wjqh_ZQrK4hh1niywsSBHvSQLm8xt0sj0693mjn34GTLg3c5xS7xqDxuN9p_i19H58OGLdtw86vXQ_Ui7uD2Jwt3n86Oz2PW635rP40u5-c25GWtfjjXl-s_Dg4H5LQb3cvJprNw_SY1eeBs6w6teS8fgRu-0L1_xw8PNQ-gF6KD1LF7snJw1_JsTUTpB2nXzTrw8ObPuW7p1cLLTaxzeje-_4IvD-0_a0dnz-MjvN8_Dr_s7T77daXmqdqF87o_6A8_9Gh_e9Z_C_n507jqD4CJoOxK4w932w6dP4L4GJ7ZlO_7t5Unr_uCmpz4cHV3bf95Zd8Hw89A5bEb3Jz0zMoyj8V70rHgnmhnKSvB4JI064M7HT9bxWPwe7un38l1w1bM6p0fPxv3VYRuP4tHn4-ZOsbs8gHvjy2AAbvXjRx63-WGLpJ_kw5kfYfpILbmYfqHJ6bWDH4UQW0G3344C8kAse8T22fcHX8Gv6tKmjgywfPBpyGQPcx1hKzq1hpPMncCeTPoS9EGwyIr2HHLomz7DlqbRBPDPjxvGpqqCOYENGGCr7LHcDzQ3T1LlbNM7DnEbd30v6ULTy5mnxwgofQQuqSVbFpQE423h6uz4y9V-bW7PoDa3ZVBj-wLbAli5nnzZscL0rVQOed0CqrEHE5MHebYFsOVa9lnFeYTkcbdtQRJryepsCzuNyb8alVgLP2wLulg7Hgxdp-sQGLF2GTi9Hg4ECgH4QnXXXnjsYy-FsSdAwmf64B98AEYH4xoSfxe69BFaIfKF_BjIWG6M5OLMCH8FltfD2-Km-vIOXGEDnOQfv5M-QoBBPHayAQPwtpATZxbx_TtNbAAe4XFgPTmDeEAfL6rNz8_GoAaCmh2B1awC1NSzvE7xWQ0esvkJ9JU6QtKtpCSF9hBcYz-lBXyEcRBAAUhe2Zi8njFcgpwKcndxGC4g-NWPha7leX4k9K0RhkzDa8wOQk391LdbRFwCFRp5a5zKHgKV0xq7FCJ9swIthKfmMwKbsUh9qzAwqdCUZo6b1ZLTZqDHVi8Gld-Bq91-7ZoR2xagPhakTW1TzF-SN8X5SygHtgviAUOqsUfqYczJHWUyaqF5HTbgX8awNDNrWFLtr2Sm2-gFGTnNTFoKQsuKYFGmgJCB1JUXRcwCs75EOQ5E7rr8cgjCj0LW1RCQKpAenEAbA1NIJQ8lFUMxehkbSbSBqdc7WWwoeTtjipYdphQZjM0oRE7BqC6-l8zfid6yVi175Jk4khyPE8rskXrqExwMvtcTjpwoww1MJkddyzmmYuwUgT4uT2wePHpiT1ZIHYRg9YirjxIC2E5JVJuEutBotGKjcaap04yhtDBROUs4CPww6oBYo37tPPCIcz21QGipwRxhEGOxIrca8C-jyGouQqAaAgkE5M1ZyTRBZ6LYEy77AYbwm_eoTdsOhXeq3NB06lXf6ahhmH_k-u451200kJL329SdCfSdEXlfLckNGf1RrBtfia_PDkLcG1wgup06yEcn6gtR35mEGaqVe37ccXHGX1Ik3hWVFq7oyo6S3Spa8_2nIYb8GXQ0jZv7JNcg6YAHlv3JIgtbS14ssC2Yop5-WZhqIEOrTDXETdPk0SnqHBuzLlI187lHLoaLEMPVvHtIuK4O4u_UBsqj5UO56wpjoh0ZvTiAXPQ5p4fsyuzaE3OHAiTu9amukAj6jqQaIhlv4Aep2tTOIKftjKdowYRU9dKjhcohvUZ91EL1gTAwwh0HVOZobAdW2LVA_w-tGDJVmmykGaqilSSooATGVL0IXIl6UcAq_ajQjUSkOBHpPVsYuGJ5Y_C4rEtOFqiDybpM78NiC8Q3Y8uuSj-QnnrcIhkVbNTVMvt0ExPYw-4IT5MJqGqw14v625ARQsJbdGMPRziAwoduwRYBXASOXUjyIiYskmBE3plXBHHtRFTW03t7-AmGozODZe_iwjv0mYKSO0DbLrw15eY4S_bYi7DrOj1SikFy5VKxlt3ec8IueQG1V0ogs6lTBjJlZN-lL2oMF0NO3tZXBnoTkEBacvMb-AI_CjLTIplUQQaJ9BmlmSi7mg-xf0VWL9y-w48wCg7G36301TgvuQiIwPdoNK5a4NWm78-pws8ldnWlruZJSmJDZgVQqkY8xLS6XjfqZhmpiZpwMSbWEWnu1cm-h1JHah1pZYSz65DJB_U0tT0pSoBnWLDpizoWSQZqyoZUVFEuplcgnAJqaWxLE_qFXC4QU8EQaRycCZ0cS6LP6B0lXap3LsTZPAIESb2grC4QOWkUpMklTStJrKcvL4L0ruuPgMPanGRnwm2PLD4UNNm5H0Dhdi8kL2dM-OyCSpKXwS4QqvS7YNksv4L8cHdSLAS4ix0oISxhNyFEbMa5L5zXDIu09lhqroWsQXUSTmqPoiHUXPE4w2cyFw5d0xdoVlKVpq-Nyta6NPABM6Hg-SRDx8GIhbppmfuSi4GVsPILDYeVMMpLPjJWAqsvaZCsBNNeaLishNFfaOCshDFeWAitBDJfcsG0EhaJL0lQrQZDL9PgWg0JtfQ0yFaDyi_zwbYaI7s2k6BbjaK-0OBbDaS9pEG4Gk5_oZGgACbXFVByXYEhLep_fObOXRoubhhUQOgLIYyFEOZCCCQuBtEWdASllOGijPw8vLeCQe0s7sTgL8EBjcDvcBYh-qotQGlmPN5aRqrqsSNRaIYh2cma1O-nVnDPut6kegEvD0GmRapIPxCuPOchxgVd7_le3FyXMBuTFbGhFsXkKUyDZFq0lq5uv-WCg94w_sgaT_rCcIG-PnyuPSjlIwuMJ3GgSwUdouLgRtvxkijOyeJvYKsrt_9mLcQotJAdx_NThfpMfpMJ1OmzR9a47Vox-F6QDPs-0zaXeI1hlk75tlO2Lz5T68hF_e2STCUPm3RwSKIkkGOCBY1HsaExHX-HiC6DfQjpTwAUdR-ZTfCkTIXKzyoylRlMyUymP7JUYgQsveYnksU0mPkUmes52zEj4dbKt6nHdcGb71elIDWS [...]

2022-01-26 02:54 UTC, Nostrademous approved these changes

2022-01-26 02:54 UTC, Nostrademous commented
LGTM

2022-01-30 17:53 UTC, LocalIdentity requested changes

2022-01-30 17:53 UTC, LocalIdentity commented on src/Data/Skills/other.lua
> +		["number_of_animated_weapons_allowed"] = {
There's no stat named this in the gem, is it a mistake?

2022-01-30 18:01 UTC, LocalIdentity approved these changes

2022-01-30 18:02 UTC, merged