Update all new league Uniques
PathOfBuildingCommunity/PathOfBuilding pull request #4098
Opened 2022-02-07 15:07 UTC by LocalIdentity

Updates all the new league uniques with their stat ranges
Adds support for Corrosion from Ceaseless Feast gloves
Adds support for Enemy Grasping Vines from Inextricable Fate boots
Adds parsing for other minor mods

2022-02-07 16:09 UTC, Nostrademous commented on src/Data/Uniques/bow.lua
> +Lose all frenzy charges on reaching maximum frenzy charges to make the next bow attack you perform fire that many additional arrows
Capitalization doesn't match poedb:
`Lose all Frenzy Charges on reaching Maximum Frenzy Charges to make the next Bow Attack you perform fire that many additional Arrows`

2022-02-09 04:59 UTC, Wires77 commented on src/Data/Uniques/Special/Generated.lua
> +		table.insert(forbidden[name], "League: Siege of the Atlas")
This makes the wording become "Exclusive to", and Siege isn't the league, so it'll be available after this league too.

We should remove these lines so they match other boss drops like Watcher's Eye, Mark of the _____, Solstice Vigil, etc. (Goes for all the uniques in this PR)
![image](https://user-images.githubusercontent.com/1209372/153124763-91d68660-57ac-4c29-ba49-9990b2b58b0c.png)

2022-02-09 05:41 UTC, Wires77 requested changes
Minor lvl requirement typo, and we should remove the "League" lines to stay consistent, but otherwise looks good

2022-02-09 05:41 UTC, Wires77 commented on src/Data/Uniques/amulet.lua
> +Requires Level 61
```suggestion
Requires Level 60
```

2022-02-09 05:46 UTC, Wires77 approved these changes

2022-02-09 05:46 UTC, merged