Support URLs in the Notes Tab
PathOfBuildingCommunity/PathOfBuilding pull request #4200
Opened 2022-02-20 05:55 UTC by pHiney

Fixes allowing URLs in Notes.

### Description of the problem being solved:
Allows a way for build creators to supply URLs to the atlas tree in their builds

### Steps taken to verify a working solution:
- Open a build, type some text in Notes.
1. Select ctrl-u and observe nothing happens.
2. Select ctrl-RightClick and observe nothing happens
- Type or paste in a URL between <>.
EG: <<http://reaper.fm>>
- Making sure the cursor in NOT in the URL, repeat steps 1 and 2 again. Observe nothing happens.
- Move the cursor into the url
- ![image](https://user-images.githubusercontent.com/4302241/154830072-cdf6f77a-1045-4f0c-8736-18e7115a803f.png)
- Repeat steps 1 and 2 again. Observe your default browser opening for each test.
- Break the url by placing a space in the http and repeat steps 1 or 2 again and note nothing happens.
- Make sure there is some text in the clipboard, move the cursor out of a URL, if one present.
3. Confirm that RightClick without Crtl down pastes (this will happen if the cursor is in a URL too)
4. Confirm that RightClick with Ctrl down does nothing.

Notes
1. I moved paste in EditControl to KeyUp
As the above process was triggering multiple browser tabs for each right click and moving the code for spawning the browser to KeyUp would trigger the paste procedure as well.
2. Spaces between <> and the URL aren't tolerated, but the regex should be able to accommodate them if people think it adds some benefit.

### Link to a build that showcases this PR:
<pre>eNqtWktz2kgQPptfoeKQW8AgwHaCk8I2tqkCh7VIsntKjUUDsx5pVNIITH799oyEURwercn6gGXx9fsx3VPufn4JhLOEOOEyvKw2aqdVB0JfTnk4v6x-ndy-P69-_lTpjplafJldpVzobz5VTrrm2RGwBIF0VUexeA7q24aT-wM5RSxUC5DhiP0r4zs5vaw-yBCqzhMLp1xt_vIFS5IHFsBl1fORuOqwxIdwer19nwEDxkNP-s-g7mKZRkbsksNqJKeIGYzGXx4nBaE8LApFnU-6Y8HWEHuKKSfBj8tqD01nc7hhAX4iNyZS0G44P2-fNVpN8-lW67uJvQhgWiBq7gOOY-jPZuArvoTrmKvrBQv9rbjTfXRlsaNUKB4JDnFBq_Y-ivvfmF9c7MNOpGLiZuy9Qpu1Zqe5ddJhOqmO6_-dq8WVQIdaSNG0g3nIFVgSjyVPZPgH9hVJ94coFQKrh4aVwRMPrbwxYiG7lgnB50M-Axqy79Fwj1hGNKTWcgwxFrqiK1uKIJfggS-xmZSRUYakYIedMAvKvmdDYCHIU9tO0tyLuoEXAmoQKhKvpVTmEDimmym9_v34Fdk5q7md1sVF56JxenrR2WuTsR9PBx4wMWIvPEgDbIUT9gxbqe7Z_r6p47YVenrgdPA_aOwg9GnJ8DWMIYF4WThUOkSCPLzbtn96kPAR5hDSlBoC-Is7PHkfmQJaObyi2oedo7Ek52jgDue0iQQlnKMJ3zindnEIXNI931k8JZRrCPF87S04CALa-LJIQvJpkYCYDkWSknb3lywpVnWjc9iaDE5LDsCpAQmmQB2VxrH8Vw9johxZLw5kGhPjkYFJBowX64T7OEaYIfQRpqlP64CvM-VILiHADDcDKU7DWzfvI70SOEdTDUe2QpSi6CnF_OcbOZ1DKSHlKbw0irDOdbZQ6W55jF5OeOEAfN8hoL_grnDNIsrspkuKKmCLJgsY8vlChThK0qW8IaHbsmAyKWHMFk4WcYtjMWkmHssVslzoRTMph8Zjfnu079UjhvDnmsz_FzhJQD-cprHOUbKMtxS_i-nWzSKunwZBJGNlXl4z4SeG5SCMUuWEZosOeOL_eEpnM70wV1FEbLb8_u1t_3oy-NbPtSiSJM9ciB9hGjzpnTL7vW0rHphO5fhSCBYlgLv2jIkEeXN89DSth93ZVyQ8DmH5Hk5B40nqxxydSAHrDZSkstnoKUi9bpOAGBUmgO6wyToCnQEJ1Wd526OgzX5NQmYLMc1As3jTwgA-W5OQr-MFCd0X0ONCn4A0r42wELLDk4bH4yzmT6kiZptZEEh66GGZZGBxICRWBw2YDzUkJfIZjoLNTwxaUuJgQQ7bDcwA051Y9qadZJtd1iw3jbFrai1xEuyYdxAkV2s8gW61e99cvQRMYSJCMNQXnROp-zDzFcTD7OIzF_YLm8uqilN8OYUZS4V-_1fKBFdr3egLb3MWuAs7yUKu9CSTsdEtIMHQDIfZNz2hcg5axkaoMWgSAzjMDIF67NStOfML_lG8Rh1MjfCAJaj7Os_9yyq2dDwK8KF9fu66VUchu8IVbuMsv53NyDXnk25_iuU-fdB09ezN18eheThZKBUlH-r11WpVi5hayBm84JRd82VQj5ANavnenCjvtaB6D3-u5j3zYxjVN5y62TVvJqBb19aY8Glz9cODxFrU35mHSsVTeKpVKkMePjvvhPq4UUTxcJ3GwiiwjppN5ar03Vx9_BWJwBhYBHFtFvz-rbOPkWuwlZGMwckVqNS0lhvtTHS-cVg5CeBptfBUrF3-U8rgHxMOHdx7YGrEotdU0t_mmeHmiYGnwQ3HkMUm8zfppYF_b2aH7kBhauSZoJ89UOZ-PE0gu_D4jhbK0LzOJGVnfQY9ADOF1Mhj7wm5mQwyoNPwVixyek_rJGHCycLmtJEKGWdZU99L-pasSSM7jLqSUiWWCu2y5YhSVyBUSZJbrKhnxyWp1NylkmvnXpoTmv8TWctOyY6dtI69N23y6UgE7gGHEVVW0I5M6tjIOZJ-d0Iu9e5RnrFrX0UNG3ktu1xo2GVe63h4KI4ty3ZXelkaTuo7bQt9LHqge0zMdO1ks2fJ8O32slV-tW2ISCVJCYSVnW1rtzYt4t6xqyTXLn3d8lnWsm_7FjndsHa-S0mIFgVkofYfDD_ESNpHoWORlfZh-IN0obZkTUusGjrUwnOPPJzTJoHSjWKvey3bBT2eNua4BD817MPQsvZW28YaSr3YJ_kRlXpBKnacbd16vkWaFd0souYOWoYzPkdEt_72v8f-A-x7BV4=
</pre>

### New descriptive text
![image](https://user-images.githubusercontent.com/4302241/154830391-d5d14997-4898-40a7-b4b4-08043cae8eca.png)

2022-06-03 06:04 UTC, Wires77 requested changes
We don't need two different hotkeys for opening a URL.  In addition, I think a double click to open a link is a lot more intuitive for users than Ctrl+Rightclick or Ctrl+u.  You could structure the logic similar to the existing double click functionality, but have the caret extend all the way until it hits whitespace on either side, then check if that's a URL instead of having to scan the entire text for a URL.

2022-06-03 06:04 UTC, Wires77 commented on src/Classes/NotesTab.lua
> +	self.controls.edit.allowURLs = true
Is this used anywhere?  Remove it if not.

2022-06-03 06:04 UTC, Wires77 commented on src/Classes/NotesTab.lua
> +	-- self.controls.normal = new("ButtonControl", {"TOPLEFT",self.controls.colorDoc,"TOPLEFT"}, 0, 32, 100, 18, colorCodes.NORMAL.."NORMAL", function() self:SetColor(colorCodes.NORMAL) end)
Remove this commented out code

2022-06-03 12:04 UTC, Nostrademous commented
@Wires77 @pHiney just a note - this allows URL's to anything in Notes, not just Atlas Passive Tree. We have to decide if it's our responsibility to restrict to specific domains only to prevent scams / malware / inappropriate materials to be potential spread through URL's enabled in Notes.

In my Trader PR I only allow very specific domains (like PoE Trade and poe.ninja) to be valid URLs.

2022-06-06 13:05 UTC, pHiney commented on src/Classes/NotesTab.lua
> +		elseif event.type == "KeyUp" then
This is described in the Notes above. To reduce multiple spawning of urls

"Notes

    I moved paste in EditControl to KeyUp
    As the above process was triggering multiple browser tabs for each right click and moving the code for spawning the browser to KeyUp would trigger the paste procedure as well."

As for using KeyDown. That is bad programming practice. The only thing on key down should be what needs to be (eg, detecting and starting drag). 
By keying things to key down you get multiple repeats of code for no reason.

2022-06-06 13:09 UTC, pHiney commented on src/Classes/NotesTab.lua
> +							os.execute('c:/windows/explorer.exe "'..entry[3]..'"')
I'm sure i tried that first and it didn't work. oh well. Does now.

2023-08-30 03:13 UTC, closed without merging