Added a button to let users search the trade website for items
PathOfBuildingCommunity/PathOfBuilding pull request #4248
Opened 2022-03-01 02:44 UTC by 13igred

Fixes # .

### Description of the problem being solved:
Not a problem more of an added feature, lets users search trade directly from PoB importing the item info right into trade. 
A new tab is opened up to the trade website on the users default browser. 

### Steps taken to verify a working solution:
- Tested with uniques, rares, flasks, cluster jewels, none have crashed the program - at the minute clusters are not searching correctly in the trade website. 

### Link to a build that showcases this PR:
- this works with any build
-
### Before screenshot:

### After screenshot:
https://ibb.co/0hFGypY
https://ibb.co/GWN8vmr

2022-03-02 08:48 UTC, 13igred commented
No, it works for rares, what are the mods on the rare? - its possible some mods are not being searched correctly. 
That message appears if no results are found on PoE trade.

2022-03-03 08:25 UTC, pHiney commented
https://pastebin.com/7z49Axga
![image](https://user-images.githubusercontent.com/4302241/156525344-1bbf1b0a-2ffa-4c86-87c3-f226bf832d75.png)
this is from the rare templates
![image](https://user-images.githubusercontent.com/4302241/156525457-8adf4cc6-82d6-4d79-934b-923d2f5915cc.png)

2022-03-03 23:48 UTC, 13igred commented
The +5 staff isn't coming up as there aren't any on trade. 
I'll change it so that it brings up trade even if there are zero results, might be more intuitive that way.

2022-06-07 02:03 UTC, Wires77 requested changes
Throwing the WIP label on this for now.  Gonna see how this interacts with #3885 as well, because they might accomplish similar things

2022-06-07 02:03 UTC, Wires77 commented on src/Classes/ItemsTab.lua
> +		httpheader = {'Content-Type: application/json', 'Accept: application/json', 'User-Agent: Path of Building/2.17 (contact: pob@mailbox.org)'},
I know this is still "WIP" but these values shouldn't be hardcoded.  Currently hard to test because we aren't in Archnemesis league anymore :)

2022-06-07 02:03 UTC, Wires77 commented on src/Classes/ItemsTab.lua
> +		os.execute(string.format('start https://www.pathofexile.com/trade/search/Scourge/%s', response.id))
Don't use os.execute, use OpenURL instead

2022-12-08 23:37 UTC, QuickStick123 commented
Superseded by https://github.com/PathOfBuildingCommunity/PathOfBuilding/pull/3885

2022-12-08 23:37 UTC, closed without merging