General improvements to "Damaging Hits" section and armour breakdown.
PathOfBuildingCommunity/PathOfBuilding pull request #4637
Opened 2022-07-23 09:34 UTC by QuickStick123

Fixes #4240.

### Description of the problem being solved:
The calculations for armour mitigations are very vague/confusing and have minimal breakdowns.
Spell suppression isn't included if it is guaranteed against spells.
Certain breakdown sections don't hide when irrelevant.

### Before Transcendence Armour Stacker
![image](https://user-images.githubusercontent.com/31533893/180598482-0c2cad92-3f6c-4dc0-b4f2-7ea43dffe5f5.png)
![image](https://user-images.githubusercontent.com/31533893/180598478-9f12f521-c06c-47a3-86dc-2b9bdcaeb2eb.png)
![image](https://user-images.githubusercontent.com/31533893/180598450-7d7a3ac9-a133-4011-8ad8-9a8a1baab217.png)
![image](https://user-images.githubusercontent.com/31533893/180598686-5b036969-45a6-42e9-aaaa-823b59ee2f3b.png)
![image](https://user-images.githubusercontent.com/31533893/180598762-35a30a09-02e1-471f-89f2-3e9bbdebbcae.png)
### After 
![image](https://user-images.githubusercontent.com/31533893/180598492-740d8227-af2d-4ac1-b5f1-2abc2c4ce35b.png)
![image](https://user-images.githubusercontent.com/31533893/180598464-baf1b854-5734-424e-8375-463b48bedbe0.png)
![image](https://user-images.githubusercontent.com/31533893/180598502-e7425fdc-6355-4cf1-8ce7-62e8f286ef66.png)
![image](https://user-images.githubusercontent.com/31533893/180598649-265d6ca0-58ab-4158-bd2a-74c05010c480.png)
![image](https://user-images.githubusercontent.com/31533893/180598758-86ae3fac-42e4-4f88-9b74-d53dc2db8fdc.png)

### Before Regular Build
![image](https://user-images.githubusercontent.com/31533893/180598840-e4048dfd-9235-4838-8e2c-387af59284c7.png)
![image](https://user-images.githubusercontent.com/31533893/180599598-d364a369-71f8-49eb-a3a9-e658d862e62b.png)
### After 
![image](https://user-images.githubusercontent.com/31533893/180598868-2738722d-42f3-4c96-9313-7046fd5f9fac.png)
![image](https://user-images.githubusercontent.com/31533893/180599584-9d1b70e6-f023-46da-bad8-d110f03b88d2.png)

### Before Enduring Cry Transcendence Without
![image](https://user-images.githubusercontent.com/31533893/180599346-9d73906d-2981-4730-ae06-4c73f75c7e8a.png)
### After
![image](https://user-images.githubusercontent.com/31533893/180599365-3ecc3aa5-40c8-4960-87a9-1628b0660d6b.png)
### Before Enduring Cry Transcendence With
![image](https://user-images.githubusercontent.com/31533893/180599403-a14eae61-1d04-4148-968d-a5c42bac0792.png)
### After
![image](https://user-images.githubusercontent.com/31533893/180599436-f25c8884-6383-4cb5-9f94-5bf09eeaba71.png)

### Spell Suppression "Spell"
![image](https://user-images.githubusercontent.com/31533893/180599023-39884681-96c9-4462-b6a3-b1ab4342729f.png)

### Spell Suppression "Average"
![image](https://user-images.githubusercontent.com/31533893/180599013-5fc2a5c9-09c3-461b-a3be-2bcb2a46ff04.png)

### Link to a build that showcases this PR:
Transcendence Armour Stacker + Phys to ele https://pobb.in/S8lGNPQF8Af8
Regular Build https://pobb.in/3XXONK_WLL2U
Enduring cry transcendence https://pobb.in/h5VqofF3ymJH

2022-07-27 04:55 UTC, Nightblade commented on src/Modules/CalcDefence.lua
> +		local spellSupressMult = 1
`supress` should be `suppress` in all your changes to this file

2022-08-08 03:54 UTC, Wires77 requested changes
I found a couple of minor improvements, but this definitely looks a lot clearer.  One thing that is outside of scope for this PR, but we'll eventually want to fix is that armour reductions should only be applying to attacks, not spells.

2022-08-08 03:54 UTC, Wires77 commented on src/Modules/CalcDefence.lua
> +			if breakdown and reductMult ~= 1 then
This reductMult is redundant

2022-08-08 03:54 UTC, Wires77 commented on src/Modules/CalcDefence.lua
> +			if suppressionEffect < 1 then
Could future-proof this by checking if it's ~= 1

2022-08-08 04:05 UTC, Wires77 approved these changes

2022-08-08 04:05 UTC, merged