Add eldritch implicits
PathOfBuildingCommunity/PathOfBuilding pull request #4658
Opened 2022-07-28 08:15 UTC by Regisle

needs feedback and testing

thoughts on changes
currently I have exarch/eater show up based on base type of the item, do I want to swap this to checking for influence instead?

I also have exarch/eater check if a mod of their type already exists in the list and replace that instead, do I want to add logic for clearing implicits to it/synth if wrong type? (eg if none of the implicts are exarch/eater wipe the list and add the mod
same with synth, if none are synth replace the whole list?) if so do I want this to be default logic, or add a button, or add a toggle?

how do I sort exarch/eater mods, they are a mess atm, it would help if I could combine groups similar to how affixes work but I am not sure its possible for this kinda addition, I could add slots for implicit on crafted items that would let me do that though

and then lastly, how do I determine which items what synth mod belongs to, they have no weights

2022-08-12 12:13 UTC, Regisle commented
jewels should have their harvest implicits

2022-08-19 02:10 UTC, Nostrademous requested changes
Outside of the one extra tab/whitespace, looks good.

2022-08-19 02:10 UTC, Nostrademous commented on src/Export/Scripts/mods.lua
> +						stats[i] = 	"While a Unique Enemy is in your Presence, ".. stat
seems to have an extra tab

2022-08-19 20:24 UTC, LocalIdentity approved these changes

2022-08-19 20:24 UTC, merged