Passive count multipliers preview on nodes
PathOfBuildingCommunity/PathOfBuilding pull request #4865
Opened 2022-08-16 15:41 UTC by Lilylicious

Fixes #4850 

### Description of the problem being solved:
When building a new tree for removing/adding nodes it was not updating the values of the multipliers for notables, masteries, or mastery types.

Mastery types are reworked to count how many are allocated per type instead of simply being true, while notables and masteries are simply adjusted so they properly include a potential new/removed node in the count.

### Steps taken to verify a working solution:
- Checked elementalist Bastion of Elements (allocated notable), unclear if it works since it does not show up on tooltip regardless, but it still adds to calc tab as it should
- Attribute masteries (allocated mastery), works great
- Trickster Polymath, works great, though recover on kill does not show up on tooltip

### Before screenshot:
(With no other masteries selected)
![image](https://user-images.githubusercontent.com/5985728/184920708-56c1bceb-2982-42bb-a66c-d25e98fe009b.png)
(With Polymath and no other masteries)
![image](https://user-images.githubusercontent.com/5985728/184921199-bf54c204-eb93-42d9-bbad-621f7649a0b7.png)

### After screenshot:
(With no other masteries selected)
![image](https://user-images.githubusercontent.com/5985728/184920817-f4e46b42-f9a3-49fd-87e2-6675fd71b1bd.png)
(With Polymath and no other masteries)
![image](https://user-images.githubusercontent.com/5985728/184921233-9c0d19f1-5948-4222-bfe4-bfc2e1143d41.png)

2022-08-16 18:46 UTC, Nostrademous requested changes

2022-08-16 18:46 UTC, Nostrademous commented on src/Modules/CalcSetup.lua
> +						allocatedNotableCount = allocatedNotableCount - 1
this should be ` + 1`

2022-08-19 16:29 UTC, Nostrademous approved these changes

2022-08-19 16:29 UTC, Nostrademous commented
LGTM

2022-12-07 12:35 UTC, LocalIdentity approved these changes

2022-12-07 12:35 UTC, merged