Prompt for saving after altering the passive search string
PathOfBuildingCommunity/PathOfBuilding pull request #5930
Opened 2023-04-05 08:09 UTC by Lilylicious

Previously, PoB did not prompt the user to save if they modified the search string, despite the fact that the search string is stored in the save.

This PR causes that prompt to happen, allowing users to remove/adjust a search and then save that change without making other changes too.

2023-04-06 05:47 UTC, Wires77 requested changes
Why are we adding a duplicate attribute in save files, here?  I think all this needs is the `searchFlag`

2023-04-06 05:47 UTC, Wires77 commented on src/Classes/PassiveTreeView.lua
> +		self.searchStrSaved = xml.attrib.searchStrSaved
This is never going to do anything.

2023-04-06 05:54 UTC, Lilylicious commented
> Why are we adding a duplicate attribute in save files, here? I think all this needs is the `searchFlag`

Grabbing the saved search string from a new save attribute was a remnant from an earlier implementation and has been corrected. The reason we have a saved search string at all though is that it allows PoB to recognize if you revert back to the same search you had before.

As an example, if you open a saved build with an empty search, add a search, and then remove it so you're back to empty, the saved string means that there's no save prompt since nothing changed from the original state. Without it, you'd be asked to save even though nothing has changed.

2023-04-07 03:44 UTC, Wires77 approved these changes

2023-04-07 03:44 UTC, merged