ux: Add icons to Socket Group skill list based on the item slot
PathOfBuildingCommunity/PathOfBuilding pull request #6339
Opened 2023-08-15 00:05 UTC by ryuukk

Fixes #5429

### Description of the problem being solved:

I was tired of clicking each items to know where they are equipped whenever i import a new build

Now it's properly displayed all at once, so i get a better understanding of where things are

LICENCE for icons: CC0 - https://ashizian.itch.io/2-bits-pack

### Steps taken to verify a working solution:
- Check Socket Group list in Skills tab
- Notice each items display proper icon based on the socket group's slot

### Link to a build that showcases this PR:

Any build will work

### Before screenshot:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/44361234/6cf692e9-3eb1-4b49-ae2b-b2e65d2b4c44)

### After screenshot:

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/44361234/a1597516-bb4b-4f43-baf6-6e66108916f7)

![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/44361234/6deb1ce0-cf7a-4309-a66f-65563638821c)

2023-08-18 16:16 UTC, Lilylicious requested changes
Once the comments I've added are resolved, this looks great. I love the idea.

2023-08-18 16:16 UTC, Lilylicious commented on src/Classes/SkillListControl.lua
> +		if disabled then
Here's a partial implementation of changing the icon depending on the item type. I strongly suggest keeping the weapon icon consistent across all weapon types, but differentiating between an off-hand weapon, a shield, and a quiver. 

You'd also need to add icons for a quiver, and possibly an off hand weapon (maybe just invert the main weapon icon on the Y axis or something?)

```suggestion
local itemsTab = self.skillsTab.build.itemsTab
		local weapon2Sel = itemsTab.activeItemSet["Weapon 2"].selItemId or 0
		local weapon2Type = itemsTab.items[weapon2Sel] and itemsTab.items[weapon2Sel].base.type or "None"

		if slot == "Weapon 2" and (weapon2Type == "Quiver" or weapon2Type == "Shield") then
			slot = weapon2Type
		elseif slot == "Weapon 2" then
			slot = "Weapon 1"
		end
		if disabled then
```

2023-08-18 16:18 UTC, Lilylicious commented on src/Classes/SkillListControl.lua
> +function SkillListClass:GetRowIcon(column, index, socketGroup)
In addition, currently the icons change colour in a way I find inconsistent. If the skill is selected as FullDPS, it's the fullDPS colour. If it's not fullDPS but it is the active skill, it's the Active colour. If neither of those, it's the same colour as the skill group label.

If you move the icon code to above the label code, then it's always white. I'd prefer that if you can't figure out how to make the colours inherit the label colour consistently.

2023-09-09 20:35 UTC, LocalIdentity approved these changes

2023-09-09 20:37 UTC, merged