Adds "Import configuration only" option
PathOfBuildingCommunity/PathOfBuilding pull request #6605
Opened 2023-09-06 09:52 UTC by jsiebern

### Description of the problem being solved:
When following a creators build guide you always come to the point where you import your own profile in order to compare to the creators guide PoB. Manually filling out the configuration can be quite tedious (you usually have to alt+tab between multiple windows). This PR attempts to make this easier by adding the `Import configuration only` option to the import dropdown. This way you can import your own build, save and then import the guides configuration on top.

### Steps taken to verify a working solution:
- Import a character
- Save
- Go to import again and enter a URL/Code, then select "Import configuration only" and click "Import"
- On success you will be taken to the configuration panel with the updated values

### Before screenshot:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/6476589/9fdf5511-9118-414e-86af-d895018d551d)

### After screenshot:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/6476589/c9102ffc-d46e-4b41-9236-6049968f98aa)

2023-09-06 10:07 UTC, Regisle commented
Could you not just import the guide first and then your character over the top?, as that deletes the items/skills/tree of the guide anyway and leaves you in the same endstate.

2023-09-06 11:44 UTC, jsiebern commented
Good point! Yeah, you could definitely import the guide first and then your character. I've run into bugs doing that before, but it was a while ago. Personally, I find the 'Import Configuration Only' option a bit more user-friendly. If the consensus is that the existing approach works fine, I understand and you're welcome to close the PR.

2023-09-11 06:20 UTC, Wires77 requested changes
I get this error when trying to import the config.  Still imports it, but shows the error.  One other thing you might want to change is have any previous configuration cleared out first, as this just adds to what is already there.
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/1209372/d61ac250-1ea8-4051-878f-b788f2410f07)

2023-09-11 06:20 UTC, Wires77 commented on src/Modules/Build.lua
> +		end
Spacing seems off here.  Plus you can remove the comment, as it no longer applies here.

2023-10-06 13:51 UTC, jsiebern commented
Closing this since there will be an update in the near futuer that adds support  for multiple configurations. I might revisit this feaure once that is implemented.

2023-10-06 13:51 UTC, closed without merging