Sort the CalcBreakdownControl list by value.
PathOfBuildingCommunity/PathOfBuilding pull request #7211
Opened 2024-01-07 23:43 UTC by duiker101

There is already a sort by type, but this is not used for a lot of breakdowns. Applying a sort by value should make it easier to read the breakdown without disrupting the sort by type.

Fixes #4433

### Description of the problem being solved:

The calculations breakdown popups are unsorted, making it harder to compare between builds.

### Steps taken to verify a working solution:
- Verified the mods are sorted in various controls

### Before screenshot:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/755683/6b3fc82f-67a9-4e06-b1a1-a97a7567d9ca)

### After screenshot:
![image](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/755683/253df90f-a3cb-45a1-998d-ede300b9e9f0)

2024-01-11 12:39 UTC, LocalIdentity approved these changes

2024-01-12 12:10 UTC, LocalIdentity requested changes
Currently doesn't sort the stat requirements for gems

2024-01-12 16:08 UTC, duiker101 commented
Added sorting for both `breakdown` and `slots` values.

![Screenshot from 2024-01-12 11-06-28](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/755683/088a6bee-b533-44aa-aff5-2c61ab661e2d)

![Screenshot from 2024-01-12 11-08-02](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/755683/3adafe0c-03e1-41c6-a72d-e05573a38768)

2024-01-13 11:13 UTC, LocalIdentity approved these changes

2024-01-13 11:13 UTC, merged

2024-01-23 22:19 UTC, ConKou commented
Is that working? I'm using the new update and I don't see any difference.
![Screenshot_84](https://github.com/PathOfBuildingCommunity/PathOfBuilding/assets/74437021/effd7647-15c0-48f9-94e5-cfba0dce3879)

2024-01-23 22:21 UTC, Wires77 commented
Yes, the value column on the left in your screenshot is sorted in descending order.  Previously it would've been in a random order (it's possible the previous listing looked similar so you didn't notice the change)

2024-01-23 22:49 UTC, ConKou commented
Yeah I'm stupid, was expecting alphabetical for some reason.